spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/rev_password_manager?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${MYSQL_USER:appuser}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD:}}

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

logging.level.com.revature=${LOGGING_LEVEL_COM_REVATURE:DEBUG}
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_ORG_HIBERNATE_SQL:DEBUG}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOGGING_LEVEL_ORG_HIBERNATE_BINDER:TRACE}

springdoc.swagger-ui.enabled=true
