package com.revature.passwordmanager.model.sharing;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Value object representing a generated share token with its metadata.
 *
 * <p>
 * Gap analysis (Feature 35) identified that this class was proposed in the spec
 * but was not implemented — token generation was handled as a plain
 * {@code String}
 * by {@link com.revature.passwordmanager.service.sharing.ShareTokenGenerator}.
 * This class now acts as a rich wrapper that carries the token value alongside
 * its creation timestamp and expected expiry, making token lifecycle easier to
 * reason about and test.
 * </p>
 *
 * <p>
 * This is intentionally <em>not</em> a JPA entity — the token string itself
 * is persisted directly on {@link SecureShare#getShareToken()}.
 * {@code ShareToken}
 * is a transient value object used in the service layer.
 * </p>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShareToken {

    /**
     * The UUID-based token string that appears in the share URL path.
     * E.g. {@code /api/shares/550e8400-e29b-41d4-a716-446655440000}
     */
    private String value;

    /**
     * When this token was generated.
     */
    private LocalDateTime createdAt;

    /**
     * When this token should expire — derived from the share's {@code expiryHours}.
     */
    private LocalDateTime expiresAt;

    // ── Factory ───────────────────────────────────────────────────────────────

    /**
     * Creates a {@code ShareToken} from a raw UUID string, setting
     * {@code createdAt} to now and computing {@code expiresAt}.
     *
     * @param tokenValue  the UUID string generated by
     *                    {@link com.revature.passwordmanager.service.sharing.ShareTokenGenerator}
     * @param expiryHours number of hours until this token expires
     * @return populated ShareToken
     */
    public static ShareToken of(String tokenValue, int expiryHours) {
        LocalDateTime now = LocalDateTime.now();
        return ShareToken.builder()
                .value(tokenValue)
                .createdAt(now)
                .expiresAt(now.plusHours(expiryHours))
                .build();
    }

    /**
     * Returns {@code true} if the token has passed its expiry timestamp.
     */
    public boolean isExpired() {
        return !LocalDateTime.now().isBefore(expiresAt);
    }

    /**
     * Returns {@code true} if the token is still within its validity window.
     */
    public boolean isValid() {
        return !isExpired();
    }
}
