/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddEmergencyContactRequest { 
    contactEmail?: string;
    contactName?: string;
    relationship?: string;
    waitingPeriodHours?: number;
}

