/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Insight } from './insight';


export interface AIInsightResponse { 
    overallAssessment?: string;
    securityScore?: number;
    insights?: Array<Insight>;
    aiPowered?: boolean;
}

