/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponse { 
    accessToken?: string;
    refreshToken?: string;
    tokenType?: string;
    username?: string;
    expiresIn?: number;
    requires2FA?: boolean;
    message?: string;
}

