/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AutofillEntry { 
    entryId?: number;
    title?: string;
    username?: string;
    websiteUrl?: string;
    matchType?: string;
    isFavorite?: boolean;
}

