/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AutofillEntry } from './autofillEntry';


export interface AutofillSuggestionResponse { 
    domain?: string;
    suggestions?: Array<AutofillEntry>;
    totalCount?: number;
}

