/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompromisedCredentialResponse } from './compromisedCredentialResponse';


export interface BreachScanResponse { 
    scanId?: number;
    entriesScanned?: number;
    compromisedFound?: number;
    status?: string;
    triggerType?: string;
    scannedAt?: string;
    newlyCompromised?: Array<CompromisedCredentialResponse>;
}

