/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScanHistoryEntry } from './scanHistoryEntry';


export interface BreachHistoryResponse { 
    scanHistory?: Array<ScanHistoryEntry>;
    totalScans?: number;
    totalCompromisedFound?: number;
}

