/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CategoryBreakdown { 
    vaultEvents?: number;
    securityEvents?: number;
    sharingEvents?: number;
    authEvents?: number;
    breachEvents?: number;
    backupEvents?: number;
}

