/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageDto } from './messageDto';


export interface ChatResponse { 
    reply?: string;
    intent?: string;
    generatedPassword?: string;
    suggestions?: Array<string>;
    timestamp?: string;
    aiPowered?: boolean;
    history?: Array<MessageDto>;
}

