/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompromisedCredentialResponse { 
    id?: number;
    vaultEntryId?: number;
    vaultEntryTitle?: string;
    username?: string;
    websiteUrl?: string;
    pwnedCount?: number;
    resolved?: boolean;
    detectedAt?: string;
    resolvedAt?: string;
}

