/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DailyActivityBucket { 
    date?: string;
    count?: number;
    vaultCount?: number;
    securityCount?: number;
    sharingCount?: number;
    authCount?: number;
    backupCount?: number;
    breachCount?: number;
}

