/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmergencyVaultEntry } from './emergencyVaultEntry';


export interface EmergencyVaultResponse { 
    ownerUsername?: string;
    expiresAt?: string;
    hoursUntilExpiry?: number;
    entries?: Array<EmergencyVaultEntry>;
}

