/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntryExpiryDetail { 
    entryId?: number;
    title?: string;
    username?: string;
    websiteUrl?: string;
    lastChangedAt?: string;
    expiresAt?: string;
    status?: string;
    daysUntilExpiry?: number;
    reminderSent?: boolean;
    snoozed?: boolean;
    snoozedUntil?: string;
}

