/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpiryPolicyResponse { 
    id?: number;
    defaultExpiryDays?: number;
    criticalExpiryDays?: number;
    reminderDaysBefore?: number;
    enabled?: boolean;
}

