/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComponentHealth } from './componentHealth';


export interface HealthResponse { 
    status?: string;
    version?: string;
    timestamp?: string;
    components?: { [key: string]: ComponentHealth; };
}

