/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HeatmapResponse { 
    accessByHour?: Array<number>;
    accessByDay?: Array<number>;
    peakHour?: number;
    peakDay?: string;
    totalAccesses?: number;
    period?: string;
}

