/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImportResult { 
    totalProcessed?: number;
    successCount?: number;
    failCount?: number;
    message?: string;
}

