/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginHistoryResponse { 
    id?: number;
    ipAddress?: string;
    deviceInfo?: string;
    location?: string;
    successful?: boolean;
    failureReason?: string;
    timestamp?: string;
}

