/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request object for authenticating a user
 */
export interface LoginRequest { 
    /**
     * The registered email or username
     */
    username: string;
    /**
     * The user\'s master password
     */
    masterPassword: string;
    captchaToken?: string;
}

