/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PasswordCategoryBreakdown { 
    categoryName?: string;
    count?: number;
    averageScore?: number;
    weakCount?: number;
}

