/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgeDistributionBucket } from './ageDistributionBucket';


export interface PasswordAgeResponse { 
    totalPasswords?: number;
    freshCount?: number;
    agingCount?: number;
    oldCount?: number;
    ancientCount?: number;
    averageAgeInDays?: number;
    distribution?: Array<AgeDistributionBucket>;
}

