/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecurityQuestionDTO } from './securityQuestionDTO';


/**
 * Request object for registering a new user
 */
export interface RegistrationRequest { 
    /**
     * User\'s email address
     */
    email: string;
    /**
     * User\'s chosen display name or login handle
     */
    username: string;
    /**
     * The highly secure master password for the vault
     */
    masterPassword: string;
    /**
     * Array of 3 security questions/answers for account recovery
     */
    securityQuestions: Array<SecurityQuestionDTO>;
    /**
     * Optional hint to remember the master password
     */
    passwordHint?: string;
}

