/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendDataPoint } from './trendDataPoint';


export interface SecurityTrendResponse { 
    trendPoints?: Array<TrendDataPoint>;
    scoreChange?: number;
    trendDirection?: string;
    periodLabel?: string;
}

