/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileItem } from './fileItem';
import { FolderItem } from './folderItem';


export interface SecureFileListResponse { 
    folders?: Array<FolderItem>;
    files?: Array<FileItem>;
    totalFiles?: number;
    totalStorageBytes?: number;
}

