/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request object for accessing a highly sensitive vault entry
 */
export interface SensitiveAccessRequest { 
    /**
     * The user\'s master password to prove identity
     */
    masterPassword: string;
    /**
     * Optional 2FA OTP token if the user has 2FA enabled
     */
    otpToken?: string;
}

