/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SharedPasswordResponse { 
    title?: string;
    username?: string;
    encryptedPassword?: string;
    encryptionIv?: string;
    websiteUrl?: string;
    permission?: string;
    viewsRemaining?: number;
    expiresAt?: string;
    sharedBy?: string;
}

