/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TeamMemberResponse { 
    memberId?: number;
    userId?: number;
    username?: string;
    email?: string;
    role?: string;
    joinedAt?: string;
}

