/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamMemberResponse } from './teamMemberResponse';


export interface TeamResponse { 
    id?: number;
    name?: string;
    description?: string;
    createdByUsername?: string;
    createdAt?: string;
    memberCount?: number;
    sharedEntryCount?: number;
    currentUserRole?: string;
    members?: Array<TeamMemberResponse>;
}

