/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntryActivitySummary } from './entryActivitySummary';
import { WeeklyActivityBucket } from './weeklyActivityBucket';


export interface TimelineSummaryResponse { 
    totalEntriesCreated?: number;
    totalPasswordChanges?: number;
    totalEntriesDeleted?: number;
    totalSharesCreated?: number;
    totalBreachDetections?: number;
    totalAuditEvents?: number;
    mostActiveDayOfWeek?: string;
    mostActiveHour?: number;
    mostAccessedEntries?: Array<EntryActivitySummary>;
    weeklyActivity?: Array<WeeklyActivityBucket>;
}

