/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DailyActivityBucket } from './dailyActivityBucket';
import { MonthlyActivityBucket } from './monthlyActivityBucket';


export interface TimelineStatsResponse { 
    eventsByType?: { [key: string]: number; };
    eventsByCategory?: { [key: string]: number; };
    dailyActivity?: Array<DailyActivityBucket>;
    monthlyActivity?: Array<MonthlyActivityBucket>;
    totalEvents?: number;
    averageEventsPerDay?: number;
    peakActivityDate?: string;
    peakActivityCount?: number;
}

