/**
 * Rev-PasswordManager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimelineEventDTO } from './timelineEventDTO';
import { CategoryBreakdown } from './categoryBreakdown';


export interface VaultTimelineResponse { 
    events?: Array<TimelineEventDTO>;
    totalEvents?: number;
    period?: string;
    startDate?: string;
    endDate?: string;
    categoryBreakdown?: CategoryBreakdown;
}

