package com.revature.passwordmanager.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Feature 41 – AI Password Assistant.
 *
 * <p>Response for {@code GET /api/ai/security-insights}.</p>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AIInsightResponse {

    /** Overall security assessment (e.g., "Your vault security is GOOD"). */
    private String overallAssessment;

    /** Security score 0-100. */
    private int securityScore;

    /** List of actionable recommendations. */
    private List<Insight> insights;

    /** Whether the insights were generated by a real LLM. */
    private boolean aiPowered;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Insight {
        /** Severity: CRITICAL, HIGH, MEDIUM, LOW, INFO. */
        private String severity;
        /** Short title of the insight. */
        private String title;
        /** Detailed description and recommendation. */
        private String description;
        /** Number of vault entries affected. */
        private int affectedCount;
    }
}
