package com.revature.passwordmanager.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Feature 41 – AI Password Assistant.
 *
 * <p>Response for {@code POST /api/ai/chat} and {@code GET /api/ai/suggestions}.</p>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ChatResponse {

    /** The AI assistant's reply text. */
    private String reply;

    /** Detected intent (e.g., GENERATE_PASSWORD, SECURITY_ANALYSIS, GENERAL). */
    private String intent;

    /** Optional generated password if the intent was GENERATE_PASSWORD. */
    private String generatedPassword;

    /** Optional quick-action suggestions for the user to click. */
    private List<String> suggestions;

    /** Timestamp of the response. */
    private LocalDateTime timestamp;

    /** Whether the response was generated by a real LLM (true) or the rule-based fallback (false). */
    private boolean aiPowered;

    /** Full conversation history (user + assistant messages). */
    private List<MessageDto> history;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MessageDto {
        private String role;
        private String content;
        private LocalDateTime createdAt;
    }
}
